### ISSUE TITLE
Does this also force players with Server Spoof in Meteor client?

### ISSUE THREAD

**Issue by DarkReaper231** [SamB440/ForcePack#20]
Meteor client has a feature called Server Spoof which makes server think we accepted the resource pack. Origin Realms somehow won't forward me to the lobby if I use it tho and I am not sure how they detect that I did loaded the resource pack. Does this have the same feature where it will just leave you in the velocity lobby if you're not loading the resource pack but just spoofing the accept?

**Comment by SamB440** [comment]
Hi, 

Yes ForcePack "detects" Meteor client. The way that client works is it just doesn't send a response to the server. That's why Origin Realms won't forward you - it's not "detecting" you at all. ForcePack prevents this by disabling player movement and interaction, as long as you have `prevent-movement` and `prevent-damage` enabled in your config.

ForcePack also blocks various other methods of resource pack bypassing, and I haven't seen a public client that works yet, however there are private bypasses that are completely undetectable, it's simply not possible to prevent bypassing 100%.

**Comment by DarkReaper231** [comment]
Okay nice, closing the issue then
